import { FormEvent, useEffect, useState } from "react";
import { NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { io } from "socket.io-client";
import { api, clearToken, getToken, saveToken, type User } from "./api";

type Listing = { id: string; title: string; description: string; location: string; rent: number; availableFrom: string; roomType: string; furnishingStatus: string; photos: string[]; status: string; match?: { score: number; explanation: string; scoringMethod: string } };
type Interest = { id: string; status: string; listing: Listing; tenant: { id: string; name: string; email: string } };
const money = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);

function Auth({ mode, onAuth }: { mode: "login" | "register"; onAuth: (user: User) => void }) {
  const navigate = useNavigate(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const values = Object.fromEntries(new FormData(event.currentTarget));
    try { const result = await api<{ user: User; token: string }>(`/auth/${mode}`, { method: "POST", body: JSON.stringify(values) }); saveToken(result.token); onAuth(result.user); navigate("/"); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <main className="auth"><section className="auth-copy"><span className="eyebrow">SMARTER RENTING</span><h1>A room is only right when the fit feels right.</h1><p>Roomly matches homes and people using budget, location and timing—not endless scrolling.</p></section><form className="card form" onSubmit={submit}><h2>{mode === "login" ? "Welcome back" : "Create your account"}</h2>{mode === "register" && <><label>Name<input name="name" required minLength={2}/></label><label>I am a<select name="role"><option value="TENANT">Tenant</option><option value="OWNER">Room owner</option></select></label></>}<label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={8} required/></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Join Roomly"}</button><p>{mode === "login" ? <>New here? <NavLink to="/register">Create an account</NavLink></> : <>Already a member? <NavLink to="/login">Sign in</NavLink></>}</p></form></main>;
}

function Profile() {
  const [message, setMessage] = useState("");
  useEffect(() => { api<Record<string, string | number> | null>("/profile").then(p => { if (!p) return; const form = document.querySelector<HTMLFormElement>("#profile-form")!; Object.entries(p).forEach(([k,v]) => { const field = form.elements.namedItem(k) as HTMLInputElement | null; if (field) field.value = k === "moveInDate" ? String(v).slice(0,10) : String(v); }); }); }, []);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const raw = Object.fromEntries(new FormData(e.currentTarget)); await api("/profile", { method: "PUT", body: JSON.stringify({ ...raw, budgetMin: Number(raw.budgetMin), budgetMax: Number(raw.budgetMax) }) }); setMessage("Preferences saved. Your scores will refresh automatically."); }
  return <Page title="Your preferences" intro="Tell us what a good fit looks like."><form id="profile-form" className="card form grid" onSubmit={submit}><label>Preferred area<input name="preferredLocation" required/></label><label>Minimum budget<input name="budgetMin" type="number" min="0" required/></label><label>Maximum budget<input name="budgetMax" type="number" min="1" required/></label><label>Move-in date<input name="moveInDate" type="date" required/></label><button>Save preferences</button>{message && <p className="success">{message}</p>}</form></Page>;
}

function Browse() {
  const [items, setItems] = useState<Listing[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function load(query="") { setLoading(true); setError(""); try { setItems(await api(`/listings${query}`)); } catch(e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function filter(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const params = new URLSearchParams(Object.entries(Object.fromEntries(new FormData(e.currentTarget))).filter(([,v])=>v) as [string,string][]); await load(`?${params}`); }
  async function interest(id: string) { try { await api("/interests", { method: "POST", body: JSON.stringify({ listingId: id }) }); alert("Interest sent to the owner."); } catch(e) { alert((e as Error).message); } }
  return <Page title="Find your next place" intro="Ranked for you, with the reasoning made visible."><form className="filters" onSubmit={filter}><input name="location" placeholder="Area or city"/><input name="budgetMin" type="number" placeholder="Min budget"/><input name="budgetMax" type="number" placeholder="Max budget"/><button>Filter</button></form>{error && <div className="notice">{error === "Tenant profile required" ? <>Create your <NavLink to="/profile">tenant profile</NavLink> before browsing.</> : error}</div>}{loading ? <p>Finding compatible rooms…</p> : <div className="cards">{items.map(x=><article className="listing card" key={x.id}>{x.photos[0] && <img src={x.photos[0]} alt=""/>}<div className="score"><strong>{x.match?.score}%</strong><span>{x.match?.scoringMethod === "LLM" ? "AI match" : "Smart match"}</span></div><h2>{x.title}</h2><p className="meta">{x.location} · {x.roomType} · {x.furnishingStatus}</p><p>{x.description}</p><div className="listing-foot"><strong>{money(x.rent)}<small>/month</small></strong><button onClick={()=>interest(x.id)}>I'm interested</button></div><details><summary>Why this score?</summary><p>{x.match?.explanation}</p></details></article>)}</div>}</Page>;
}

function OwnerListings() {
  const [items,setItems]=useState<Listing[]>([]); const load=()=>api<Listing[]>("/listings/mine").then(setItems); useEffect(()=>{void load()},[]);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const raw=Object.fromEntries(new FormData(e.currentTarget)); await api("/listings",{method:"POST",body:JSON.stringify({...raw,rent:Number(raw.rent),photos:String(raw.photos||"").split(",").map(v=>v.trim()).filter(Boolean)})}); e.currentTarget.reset(); await load(); }
  async function fill(id:string){await api(`/listings/${id}/fill`,{method:"PATCH"});await load()}
  return <Page title="Your rooms" intro="Publish availability and manage it from one place."><details className="card create"><summary>Add a room</summary><form className="form grid" onSubmit={submit}><label>Title<input name="title" required/></label><label>Location<input name="location" required/></label><label>Monthly rent<input name="rent" type="number" min="1" required/></label><label>Available from<input name="availableFrom" type="date" required/></label><label>Room type<input name="roomType" placeholder="Single, shared, 1BHK…" required/></label><label>Furnishing<input name="furnishingStatus" placeholder="Full, semi, unfurnished" required/></label><label className="wide">Description<textarea name="description" minLength={10} required/></label><label className="wide">Photo URLs, comma separated<input name="photos"/></label><button>Publish room</button></form></details><div className="cards">{items.map(x=><article className="card listing" key={x.id}><span className={`pill ${x.status.toLowerCase()}`}>{x.status}</span><h2>{x.title}</h2><p>{x.location} · {money(x.rent)}</p>{x.status==="ACTIVE"&&<button className="secondary" onClick={()=>fill(x.id)}>Mark filled</button>}</article>)}</div></Page>;
}

function Interests({ user }: { user: User }) {
  const [items,setItems]=useState<Interest[]>([]); const load=()=>api<Interest[]>("/interests/mine").then(setItems); useEffect(()=>{void load()},[]);
  async function answer(id:string,status:string){await api(`/interests/${id}`,{method:"PATCH",body:JSON.stringify({status})});await load()}
  return <Page title="Interests" intro={user.role==="OWNER"?"Review people who like your rooms.":"Track your requests and accepted chats."}><div className="stack">{items.map(x=><article className="card interest" key={x.id}><div><span className={`pill ${x.status.toLowerCase()}`}>{x.status}</span><h2>{x.listing.title}</h2><p>{user.role==="OWNER"?`${x.tenant.name} · ${x.tenant.email}`:x.listing.location}</p></div><div className="actions">{user.role==="OWNER"&&x.status==="PENDING"&&<><button onClick={()=>answer(x.id,"ACCEPTED")}>Accept</button><button className="secondary" onClick={()=>answer(x.id,"DECLINED")}>Decline</button></>}{x.status==="ACCEPTED"&&<NavLink className="button" to={`/chat/${x.id}`}>Open chat</NavLink>}</div></article>)}</div></Page>;
}

function Chat() {
  const {id=""}=useParams(); const [messages,setMessages]=useState<Array<{id:string;content:string;createdAt:string;sender:{name:string}}>>([]); const [error,setError]=useState("");
  useEffect(()=>{api<typeof messages>(`/chat/${id}/messages`).then(setMessages).catch(e=>setError(e.message)); const socket=io({auth:{token:getToken()}}); socket.emit("join_room",{interestId:id}); socket.on("message_received",m=>setMessages(old=>old.some(x=>x.id===m.id)?old:[...old,m])); return()=>{socket.disconnect()};},[id]);
  function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const content=String(new FormData(form).get("content"));const socket=io({auth:{token:getToken()}});socket.emit("join_room",{interestId:id},()=>socket.emit("send_message",{interestId:id,content},(r:{ok:boolean;error?:string})=>{if(r.ok)form.reset();else setError(r.error||"Could not send");socket.disconnect()}));}
  return <Page title="Conversation" intro="This private chat opened when the interest was accepted.">{error&&<p className="error">{error}</p>}<div className="chat card">{messages.map(m=><div className="message" key={m.id}><strong>{m.sender.name}</strong><p>{m.content}</p><time>{new Date(m.createdAt).toLocaleString()}</time></div>)}</div><form className="composer" onSubmit={send}><input name="content" maxLength={2000} placeholder="Write a message…" required/><button>Send</button></form></Page>;
}

function Admin(){const [stats,setStats]=useState<Record<string,number>>({});const [users,setUsers]=useState<Array<User&{active:boolean}>>([]);useEffect(()=>{void Promise.all([api<Record<string,number>>("/admin/activity").then(setStats),api<typeof users>("/admin/users").then(setUsers)])},[]);return <Page title="Platform activity" intro="A clean view across users, listings and successful connections."><div className="stats">{Object.entries(stats).map(([k,v])=><div className="card" key={k}><strong>{v}</strong><span>{k.replace(/([A-Z])/g," $1")}</span></div>)}</div><div className="card table"><h2>Users</h2>{users.map(u=><div key={u.id}><span>{u.name}<small>{u.email}</small></span><span>{u.role} · {u.active?"Active":"Disabled"}</span></div>)}</div></Page>}

function Page({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <main className="page"><header className="page-head"><span className="eyebrow">ROOMLY</span><h1>{title}</h1><p>{intro}</p></header>{children}</main>}
function Shell({user,logout}:{user:User;logout:()=>void}){return <><nav><NavLink className="brand" to="/">roomly<span>.</span></NavLink><div>{user.role==="TENANT"&&<><NavLink to="/">Browse</NavLink><NavLink to="/profile">Preferences</NavLink><NavLink to="/interests">Interests</NavLink></>}{user.role==="OWNER"&&<><NavLink to="/">Listings</NavLink><NavLink to="/interests">Interests</NavLink></>}{user.role==="ADMIN"&&<NavLink to="/">Admin</NavLink>}<button className="ghost" onClick={logout}>Sign out</button></div></nav><Routes><Route path="/" element={user.role==="TENANT"?<Browse/>:user.role==="OWNER"?<OwnerListings/>:<Admin/>}/><Route path="/profile" element={user.role==="TENANT"?<Profile/>:<Navigate to="/"/>}/><Route path="/interests" element={<Interests user={user}/>}/><Route path="/chat/:id" element={<Chat/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></>}
export function App(){const [user,setUser]=useState<User|null>(null);const [ready,setReady]=useState(false);useEffect(()=>{if(!getToken()){setReady(true);return}api<User>("/auth/me").then(setUser).catch(clearToken).finally(()=>setReady(true))},[]);if(!ready)return <div className="loading">roomly<span>.</span></div>;if(!user)return <Routes><Route path="/register" element={<Auth mode="register" onAuth={setUser}/>}/><Route path="*" element={<Auth mode="login" onAuth={setUser}/>}/></Routes>;return <Shell user={user} logout={()=>{clearToken();setUser(null)}}/>}
